name: Update Rates
on:
  schedule:
    - cron: '0,10,20,30,40,50 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Wait for 30s
        run: sleep 30
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python update_rates.py # MUST MATCH FILENAME
      - name: Deploy
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add index.html
          git commit -m "Auto Update Rates" || exit 0
          git push
