name: Live Price Update
on:
  schedule:
    # Runs at the start of every 10th minute
    - cron: '0,10,20,30,40,50 * * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Wait for 30 Seconds
        run: sleep 30  # This ensures it fetches at exactly :30 seconds past the minute
      - name: Run Update
        run: |
          pip install requests
          python update_rates.py
      - name: Push to GitHub
        run: |
          git config --global user.name "Bot"
          git config --global user.email "bot@github.com"
          git add index.html
          git commit -m "API Sync: $(date)" || exit 0
          git push
